### ISSUE TITLE
Allow inputing policies directly into the yaml file, without pointing to a file  

### ISSUE THREAD

**Issue by jbtrystram** [seedwing-io/seedwing-action#4]
```yaml
policy: |
  pattern not-affected = cyclonedx::component-purls | lang::map<uri::purl> | osv::from-purl | openvex::from-osv | list::none<openvex::affected>
name: vulnerabilities::not-affected
```
